all: consecutive spawn increment

consecutive: consecutive.c
	gcc -o consecutive consecutive.c
spawn: spawn.c
	gcc -std=c99 -o spawn spawn.c
increment: increment.c
	gcc -std=c99 -o increment increment.c
